import 'palette.dart';

const shoes = [
  {
    'background': jordan_background,
    'info_background': jordan_yellow,
    'asset': 'assets/air_jordans.png',
    'price_colour': jordan_yellow,
    'rect_colour': jordan_yellow,
    'price': '\$248',
    'name': 'Air Jordan 5 Laney JSP',
    'name_colour': background,
    'size_colour': primary,
    'size_selected': background,
    'size_unselected': background,
    'border': background,
    'cart_button': jordan_blue,
  },
  {
    'background': high_background,
    'info_background': primary,
    'asset': 'assets/high_x.png',
    'price_colour': primary,
    'rect_colour': primary,
    'price': '\$232',
    'name': 'High x Emotionally',
    'name_colour': background,
    'size_colour': high_red,
    'size_selected': primary,
    'size_unselected': background,
    'border': background,
    'cart_button': high_red,
  },
  {
    'background': air_background,
    'info_background': air_orange,
    'asset': 'assets/nike_air.png',
    'price_colour': primary,
    'rect_colour': air_light_blue,
    'price': '\$258',
    'name': 'Nike Air Flightposite',
    'name_colour': primary,
    'size_colour': primary,
    'size_selected': air_orange,
    'size_unselected': primary,
    'border': primary,
    'cart_button': air_blue,
  },
];